### ISSUE TITLE
Diagram Client-Side-Rendering is slow

### ISSUE THREAD

**Issue by endeffects** [syncfusion/ej2-blazor-samples#50]
I switched my application from server to client side rendering
and noticed that rendering the diagram tooks much longer now.

Do you plan to improve the performance here?
I don't want to have the extra load on top of my server for rendering
and also i don't want to use extra (blazor) signalr sockets for it.

![image](https://user-images.githubusercontent.com/13432569/60759327-c4f1ef00-a023-11e9-9950-d082375f2f83.png)

**Comment by RamyaThiru** [comment]
HI,


  | Hello word   application        Time   taken  - seconds | Referring   ej2.min.js        Time   taken  - seconds | Referring   individual component file ej2.diagram.        Time   taken  - seconds
-- | -- | -- | --
Client   Side | 4.55 | 10.55 | 9.64
Server   side | 1 | 3.9 | 1.9

We have created performance comparison document with screenshots. Please refer to the comparison document as below.

Document : https://www.syncfusion.com/downloads/support/directtrac/general/doc/Performance_Comparison547272365

Hence, the performance delay is not specific to our control, but it is occurring for all the client side Blazor applications.

In the client side application, it is expected to have few more seconds during initial loading since it is downloading the needed resources to client browser, but it will save the back and forth communication between server and client browser once it is deployed and initialized.

Regards,
Ramya T

**Comment by endeffects** [comment]
Thank you for the investigation, i thought the new web assembly technology offers a much better performance. I found similar reports on the web, that the client side performance is currently bad. This issue seems to be related to the mono framework itself. Hopefully they get this fixed soon.
